name: CI
on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-base:
    uses: ./.github/workflows/lint_and_test.yml
    with:
      install: poetry install
      lint: false
      run: poetry run make test-base
      python-versions: '["3.6"]'

  test-python36:
    uses: ./.github/workflows/lint_and_test.yml
    with:
      install: make install
      python-versions: '["3.6"]'
      lint: false

  test-sqlalchemy13:
    uses: ./.github/workflows/lint_and_test.yml
    with:
      install: make install
      sqlalchemy-versions: '["1.3.24"]'
      python-versions: '["3.7", "3.8", "3.9", "3.10"]'
      lint: false

  test-pytest-asyncio-gt-16:
    uses: ./.github/workflows/lint_and_test.yml
    with:
      install: make install
      pytest-asyncio-versions: '["0.19"]'
      sqlalchemy-versions: '["1.4.39"]'
      python-versions: '["3.7"]'
      lint: false

  test-no-extras:
    uses: ./.github/workflows/lint_and_test.yml
    with:
      install: make install-base
      run: poetry run make test-base
      sqlalchemy-versions: '["1.4.39"]'
      python-versions: '["3.7", "3.8", "3.9", "3.10"]'

  test-and-lint:
    uses: ./.github/workflows/lint_and_test.yml
    with:
      install: make install
      sqlalchemy-versions: '["1.4.39"]'
      python-versions: '["3.7", "3.8", "3.9", "3.10"]'
